import path from "node:path";
import {
  copyD3Asset,
  ensureDir,
  EXPERIMENTS,
  FIGURE_ROOT,
  mean,
  median,
  readJson,
  relativeArtifact,
  TABLE_ROOT,
  writeText,
} from "./lib/experiment-utils.mjs";

await ensureDir(FIGURE_ROOT);
await ensureDir(TABLE_ROOT);
await copyD3Asset();

const results = {
  e1: await readExperiment(EXPERIMENTS.e1, "zero-install-results.json"),
  e2: await readExperiment(EXPERIMENTS.e2, "adapter-fidelity-results.json"),
  e3: await readExperiment(EXPERIMENTS.e3, "reference-check-results.json"),
  e4: await readExperiment(EXPERIMENTS.e4, "browser-runtime-results.json"),
  e6: await readExperiment(EXPERIMENTS.e6, "compatibility-results.json"),
};

const figures = [
  ["figure-e1-zero-install.html", "E1 Zero-install Timing", e1FigureSpec(results.e1)],
  ["figure-e2-adapter-fidelity.html", "E2 Adapter Fidelity", e2FigureSpec(results.e2)],
  ["figure-e3-reference-checks.html", "E3 Reference Checks", e3FigureSpec(results.e3)],
  ["figure-e4-browser-runtime.html", "E4 Browser Runtime", e4FigureSpec(results.e4)],
  ["figure-e6-compatibility.html", "E6 Compatibility", e6FigureSpec(results.e6)],
];

for (const [file, title, spec] of figures) {
  await writeText(path.join(FIGURE_ROOT, file), figurePage(title, spec));
}

const tables = [
  ["table-e1-zero-install.html", e1Table(results.e1)],
  ["table-e2-adapter-fidelity.html", e2Table(results.e2)],
  ["table-e3-reference-checks.html", e3Table(results.e3)],
  ["table-e4-browser-runtime.html", e4Table(results.e4)],
  ["table-e6-compatibility.html", e6Table(results.e6)],
];

for (const [file, table] of tables) {
  await writeText(path.join(TABLE_ROOT, file), standaloneTable(table));
}
await writeText(
  path.join(TABLE_ROOT, "all-google-doc-tables.html"),
  combinedTables(tables.map(([, table]) => table))
);
await writeText(
  path.join(TABLE_ROOT, "README.md"),
  `# Google Docs Tables\n\nGenerated by \`npm run assets:manuscript\` from the E1/E2/E3/E4/E6 result JSON files. Each table is standalone HTML with inline table styles for copy/paste into Google Docs or Word.\n`
);
await writeText(
  path.join(FIGURE_ROOT, "README.md"),
  `# Manuscript Figures\n\nGenerated D3-backed HTML figures for the replacement E1/E2/E3/E4/E6 experiment suite. The pages load \`../assets/d3.min.js\` locally and do not depend on Plotly.\n`
);

for (const [file] of figures) {
  console.log(`Wrote ${relativeArtifact(path.join(FIGURE_ROOT, file))}`);
}
for (const [file] of tables) {
  console.log(`Wrote ${relativeArtifact(path.join(TABLE_ROOT, file))}`);
}
console.log(`Wrote ${relativeArtifact(path.join(TABLE_ROOT, "all-google-doc-tables.html"))}`);

async function readExperiment(experiment, file) {
  const resultPath = path.join(experiment.dir, "data", file);
  return await readJson(resultPath, {
    schemaVersion: "msig.manuscript.experiment.v1",
    generatedAt: null,
    experimentId: experiment.id,
    environment: {},
    inputs: {},
    rows: [],
    artifacts: {},
    status: "missing",
    notes: [`Missing result file: ${relativeArtifact(resultPath)}`],
  });
}

function e1FigureSpec(result) {
  const row = result.rows?.[0] || {};
  const steps = Array.isArray(row.steps) && row.steps.length
    ? row.steps.map((step) => ({ label: step.name, value: Number(step.elapsedSeconds) || 0 }))
    : [{ label: result.status, value: Number(row.elapsedSeconds) || 0.1 }];
  return {
    kind: "timeline",
    subtitle: "Seconds from blank harness page load to SDK report-ready event.",
    xLabel: "Elapsed seconds",
    data: steps,
  };
}

function e2FigureSpec(result) {
  const rows = (result.rows || []).map((row) => ({
    label: row.tool,
    value: Number(row.meanExposureCosine) || 0,
    secondary: Number(row.maxAbsoluteExposureDifference) || 0,
    status: row.status,
  }));
  return {
    kind: "bar",
    subtitle: "Mean browser-vs-local exposure cosine for completed adapter pairs.",
    yLabel: "Mean exposure cosine",
    data: rows.length ? rows : [{ label: result.status, value: 0, status: result.status }],
  };
}

function e3FigureSpec(result) {
  return {
    kind: "status",
    subtitle: "Numerical agreement checks against independent reference implementations.",
    data: (result.rows || []).map((row) => ({
      label: row.checkId,
      value: row.status === "pass" ? 1 : 0,
      status: row.status,
      detail:
        row.maxAbsoluteDifference ??
        row.maxMetricDelta ??
        row.reconstructionErrorRatio ??
        null,
    })),
  };
}

function e4FigureSpec(result) {
  const completed = (result.rows || []).filter((row) => row.status === "completed");
  const grouped = new Map();
  for (const row of completed) {
    const key = `${row.browser}|${row.scenario}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(Number(row.elapsedMs) || 0);
  }
  const data = [...grouped.entries()].map(([key, values]) => {
    const [browser, scenario] = key.split("|");
    const scenarioLabel =
      {
        single_sample_fit_report: "fit/report",
        medium_cohort_120: "120-sample cohort",
        portal_scale_300x40: "300x40 refit",
        bootstrap_500: "bootstrap",
        nmf_rank_selection_rank4: "NMF rank/extract",
      }[scenario] || scenario.replaceAll("_", " ");
    return {
      label: `${browser} ${scenarioLabel}`,
      browser,
      scenario,
      value: median(values) / 1000,
    };
  });
  return {
    kind: "bar",
    subtitle: "Median elapsed seconds across completed browser benchmark repeats.",
    yLabel: "Median seconds",
    data: data.length ? data : [{ label: result.status, value: 0, status: result.status }],
  };
}

function e6FigureSpec(result) {
  const checks = ["sdkImport", "publicFetch", "fitReport", "d3Render"];
  const data = [];
  for (const row of result.rows || []) {
    for (const check of checks) {
      data.push({
        row: `${row.browser} (${row.device})`,
        column: check,
        status: row[check],
      });
    }
  }
  return {
    kind: "matrix",
    subtitle: "Automated desktop browser rows only.",
    data: data.length ? data : [{ row: result.status, column: "status", status: result.status }],
  };
}

function figurePage(title, spec) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(title)}</title>
    <script src="../assets/d3.min.js"></script>
    <style>
      body { margin: 0; font-family: Arial, sans-serif; color: #172026; background: #ffffff; }
      main { max-width: 1040px; margin: 0 auto; padding: 28px; }
      h1 { margin: 0 0 6px; font-size: 26px; }
      p { margin: 0 0 18px; color: #53616f; }
      svg { width: 100%; height: auto; overflow: visible; }
      .axis text { fill: #53616f; font-size: 12px; }
      .axis path, .axis line { stroke: #aab6c2; }
    </style>
  </head>
  <body>
    <main>
      <div id="chart"></div>
    </main>
    <script>
      const spec = ${JSON.stringify(spec)};
      const colors = { pass: "#0b6b4f", completed: "#2f6f73", failed: "#b4473a", missing: "#69737f", blocked: "#b4473a", "not available": "#69737f" };
      if (spec.kind === "matrix") renderMatrix(spec);
      else if (spec.kind === "status") renderStatus(spec);
      else renderBar(spec);

      function renderBar(spec) {
        const data = spec.data || [];
        const margin = { top: 24, right: 36, bottom: 160, left: 100 };
        const width = 1040;
        const height = 640;
        const svg = d3.select("#chart").append("svg").attr("viewBox", [0, 0, width, height]);
        const x = d3.scaleBand().domain(data.map((d) => d.label)).range([margin.left, width - margin.right]).padding(0.22);
        const maxValue = d3.max(data, (d) => d.value) || 1;
        const y = d3.scaleLinear().domain([0, maxValue * 1.12]).nice().range([height - margin.bottom, margin.top]);
        svg.append("g").attr("class", "axis").attr("transform", "translate(0," + (height - margin.bottom) + ")").call(d3.axisBottom(x)).selectAll("text").attr("transform", "rotate(-35)").style("text-anchor", "end");
        svg.append("g").attr("class", "axis").attr("transform", "translate(" + margin.left + ",0)").call(d3.axisLeft(y).ticks(6));
        svg.selectAll("rect").data(data).join("rect")
          .attr("x", (d) => x(d.label))
          .attr("y", (d) => y(d.value))
          .attr("width", x.bandwidth())
          .attr("height", (d) => y(0) - y(d.value))
          .attr("fill", (d) => colors[d.status] || "#2f6f73");
        svg.selectAll(".value").data(data).join("text")
          .attr("x", (d) => x(d.label) + x.bandwidth() / 2)
          .attr("y", (d) => y(d.value) - 6)
          .attr("text-anchor", "middle")
          .attr("font-size", 12)
          .text((d) => Number.isFinite(d.value) ? d.value.toFixed(d.value < 1 ? 3 : 1) : "");
        svg.append("text").attr("x", 18).attr("y", 18).attr("font-size", 12).attr("fill", "#53616f").text(spec.yLabel || spec.xLabel || "");
      }

      function renderStatus(spec) {
        const data = spec.data && spec.data.length ? spec.data : [{ label: "missing", value: 0, status: "missing" }];
        const margin = { top: 20, right: 24, bottom: 30, left: 260 };
        const width = 980;
        const height = Math.max(180, data.length * 58 + margin.top + margin.bottom);
        const svg = d3.select("#chart").append("svg").attr("viewBox", [0, 0, width, height]);
        const y = d3.scaleBand().domain(data.map((d) => d.label)).range([margin.top, height - margin.bottom]).padding(0.22);
        svg.append("g").attr("class", "axis").attr("transform", "translate(" + margin.left + ",0)").call(d3.axisLeft(y));
        svg.selectAll("rect").data(data).join("rect")
          .attr("x", margin.left + 20)
          .attr("y", (d) => y(d.label))
          .attr("width", 160)
          .attr("height", y.bandwidth())
          .attr("fill", (d) => colors[d.status] || "#69737f");
        svg.selectAll(".status-label").data(data).join("text")
          .attr("x", margin.left + 100)
          .attr("y", (d) => y(d.label) + y.bandwidth() / 2 + 5)
          .attr("text-anchor", "middle")
          .attr("fill", "#fff")
          .attr("font-weight", 700)
          .text((d) => d.status || "");
        svg.selectAll(".detail").data(data).join("text")
          .attr("x", margin.left + 210)
          .attr("y", (d) => y(d.label) + y.bandwidth() / 2 + 5)
          .attr("font-size", 12)
          .attr("fill", "#53616f")
          .text((d) => d.detail === null || d.detail === undefined ? "" : String(Number(d.detail).toExponential ? Number(d.detail).toExponential(2) : d.detail));
      }

      function renderMatrix(spec) {
        const data = spec.data || [];
        const rows = [...new Set(data.map((d) => d.row))];
        const columns = [...new Set(data.map((d) => d.column))];
        const cell = 42;
        const margin = { top: 74, right: 24, bottom: 24, left: 230 };
        const width = margin.left + columns.length * cell + margin.right;
        const height = margin.top + rows.length * cell + margin.bottom;
        const svg = d3.select("#chart").append("svg").attr("viewBox", [0, 0, width, height]);
        svg.selectAll(".col").data(columns).join("text")
          .attr("x", (_, i) => margin.left + i * cell + cell / 2)
          .attr("y", margin.top - 10)
          .attr("text-anchor", "end")
          .attr("transform", (_, i) => "rotate(-35," + (margin.left + i * cell + cell / 2) + "," + (margin.top - 10) + ")")
          .attr("font-size", 12)
          .text((d) => d);
        svg.selectAll(".row").data(rows).join("text")
          .attr("x", margin.left - 10)
          .attr("y", (_, i) => margin.top + i * cell + cell / 2 + 5)
          .attr("text-anchor", "end")
          .attr("font-size", 12)
          .text((d) => d);
        svg.selectAll("rect").data(data).join("rect")
          .attr("x", (d) => margin.left + columns.indexOf(d.column) * cell)
          .attr("y", (d) => margin.top + rows.indexOf(d.row) * cell)
          .attr("width", cell - 4)
          .attr("height", cell - 4)
          .attr("fill", (d) => colors[d.status] || "#69737f");
      }
    </script>
  </body>
</html>`;
}

function e1Table(result) {
  const rows = (result.rows || []).map((row) => ({
    Browser: row.browser || row.browserId || "missing",
    Status: row.status || result.status,
    "Elapsed seconds": formatNumber(row.elapsedSeconds, 3),
    Samples: row.sampleCount ?? "",
    Signatures: row.signatureCount ?? "",
    "Report bytes": row.reportBytes ?? "",
  }));
  return {
    caption: "Table E1. Zero-install browser demonstration.",
    note: "Elapsed time is measured from harness page load to SDK report-ready event in a fresh browser profile.",
    columns: ["Browser", "Status", "Elapsed seconds", "Samples", "Signatures", "Report bytes"],
    rows: rows.length ? rows : [{ Browser: "missing", Status: result.status, "Elapsed seconds": "", Samples: "", Signatures: "", "Report bytes": "" }],
  };
}

function e2Table(result) {
  const rows = (result.rows || []).map((row) => ({
    Tool: row.tool,
    "Browser runtime": row.browserRuntime,
    "Local runtime": row.localRuntime,
    "Mean cosine": formatNumber(row.meanExposureCosine, 6),
    "Median cosine": formatNumber(row.medianExposureCosine, 6),
    "Minimum cosine": formatNumber(row.minExposureCosine, 6),
    "Max abs diff": formatSci(row.maxAbsoluteExposureDifference),
    RMSE: formatSci(row.rmse),
    "Top-signature concordance": formatPercent(row.topSignatureConcordance),
  }));
  return {
    caption: "Table E2. Browser adapter fidelity against local package execution.",
    note: "The same 38 PCAWG Lung-AdenoCA SBS96 spectra and full 67-signature COSMIC v3 SBS96 catalog were used for every browser/local comparator pair.",
    columns: ["Tool", "Browser runtime", "Local runtime", "Mean cosine", "Median cosine", "Minimum cosine", "Max abs diff", "RMSE", "Top-signature concordance"],
    rows: rows.length ? rows : [{ Tool: "No completed pairs", "Browser runtime": "", "Local runtime": "", "Mean cosine": "", "Median cosine": "", "Minimum cosine": "", "Max abs diff": "", RMSE: "", "Top-signature concordance": "" }],
  };
}

function e3Table(result) {
  const rowsById = new Map((result.rows || []).map((row) => [row.checkId, row]));
  const scipyNnls = rowsById.get("nnls_vs_scipy");
  const rNnls = rowsById.get("nnls_vs_r_nnls");
  const nmf = rowsById.get("nmf_vs_sklearn");
  const nnlsMax = Math.max(
    Number(scipyNnls?.maxAbsoluteDifference) || 0,
    Number(rNnls?.maxAbsoluteDifference) || 0
  );
  const nnlsMargin = nnlsMax > 0 ? Math.floor((Number(scipyNnls?.threshold) || 1e-6) / nnlsMax) : "";
  const rows = [
    {
      "SDK area": "NNLS signature fitting",
      "Independent reference": `${scipyNnls?.reference || "scipy.optimize.nnls"} and ${rNnls?.reference || "R nnls::nnls"}`,
      "What was checked": `Largest absolute difference in fitted exposure coefficients across ${scipyNnls?.sampleCount || rNnls?.sampleCount || ""} spectra.`,
      Outcome: `${formatSci(nnlsMax)}, about ${formatInteger(nnlsMargin)}x below the pre-set 1e-6 reproducibility bound.`,
    },
    {
      "SDK area": "NMF extraction",
      "Independent reference": nmf?.reference || "scikit-learn NMF",
      "What was checked": `Reconstruction error and similarity of matched NMF components across ${nmf?.sampleCount || ""} planted low-rank spectra.`,
      Outcome: `SDK reconstruction error was ${formatNumber(nmf?.reconstructionErrorRatio, 3)}x the reference, with median component cosine ${formatNumber(nmf?.medianMatchedComponentCosine, 3)}; this met the pre-set rule of no more than 5% worse reconstruction error and cosine >= 0.95.`,
    },
  ];
  return {
    caption: "Table E3. Internal numerical solver reference checks.",
    note: "Validation bounds were set before inspecting these results and are numerical reproducibility checks, not biological decision cutoffs. NNLS fitting is expected to match independent solvers up to floating-point tolerance. NMF is stochastic and non-unique, so it was evaluated by reconstruction error and matched-component cosine rather than exact matrix equality.",
    columns: ["SDK area", "Independent reference", "What was checked", "Outcome"],
    rows: rows.length ? rows : [{ "SDK area": "missing", "Independent reference": "", "What was checked": "", Outcome: result.status }],
  };
}

function e4Table(result) {
  const grouped = new Map();
  for (const row of result.rows || []) {
    const key = `${row.browser}|${row.scenario}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(row);
  }
  const rows = [...grouped.entries()].map(([key, group]) => {
    const [browser, scenario] = key.split("|");
    const completed = group.filter((row) => row.status === "completed");
    return {
      Browser: browser,
      Scenario: scenario,
      Repeats: completed.length || "",
      "Median seconds": completed.length ? formatNumber(median(completed.map((row) => Number(row.elapsedMs) || 0)) / 1000, 3) : "",
      "Mean seconds": completed.length ? formatNumber(mean(completed.map((row) => Number(row.elapsedMs) || 0)) / 1000, 3) : "",
      Status: completed.length ? "completed" : group[0]?.status || result.status,
    };
  });
  return {
    caption: "Table E4. Browser runtime benchmarks.",
    note: "Each available browser is run for five repeats per scenario by default; unavailable browsers are explicitly retained.",
    columns: ["Browser", "Scenario", "Repeats", "Median seconds", "Mean seconds", "Status"],
    rows: rows.length ? rows : [{ Browser: "missing", Scenario: "", Repeats: "", "Median seconds": "", "Mean seconds": "", Status: result.status }],
  };
}

function e6Table(result) {
  const rows = (result.rows || []).map((row) => ({
    Source: row.source,
    Browser: row.browser,
    Device: row.device,
    "SDK import": row.sdkImport,
    "Public fetch": row.publicFetch,
    "Fit/report": row.fitReport,
    "D3 render": row.d3Render,
    "Pyodide adapter": row.pyodideAdapter,
    "WebR adapter": row.webrAdapter,
    Status: row.status,
  }));
  return {
    caption: "Table E6. Desktop browser compatibility matrix.",
    note: "Rows are automated desktop checks on the benchmark host.",
    columns: ["Source", "Browser", "Device", "SDK import", "Public fetch", "Fit/report", "D3 render", "Pyodide adapter", "WebR adapter", "Status"],
    rows: rows.length ? rows : [{ Source: "missing", Browser: "", Device: "", "SDK import": result.status, "Public fetch": "", "Fit/report": "", "D3 render": "", "Pyodide adapter": "", "WebR adapter": "", Status: result.status }],
  };
}

function standaloneTable(table) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>${escapeHtml(table.caption)}</title>
  </head>
  <body>
    ${tableHtml(table)}
  </body>
</html>`;
}

function combinedTables(tables) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>mSigSDK Manuscript Tables E1-E6</title>
  </head>
  <body>
    ${tables.map(tableHtml).join("\n<hr style=\"border:0;border-top:1px solid #d7dde3;margin:28px 0;\">\n")}
  </body>
</html>`;
}

function tableHtml(table) {
  const tableStyle = "border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:10.5pt;color:#172026;";
  const thStyle = "border:1px solid #9aa7b3;background:#eaf0f4;padding:6px;text-align:left;font-weight:700;";
  const tdStyle = "border:1px solid #b9c3cc;padding:6px;vertical-align:top;";
  const captionStyle = "caption-side:top;text-align:left;font-weight:700;font-size:11.5pt;margin-bottom:6px;";
  const noteStyle = "font-family:Arial,sans-serif;font-size:9.5pt;color:#53616f;margin-top:6px;";
  return `<table style="${tableStyle}">
  <caption style="${captionStyle}">${escapeHtml(table.caption)}</caption>
  <thead><tr>${table.columns.map((column) => `<th style="${thStyle}">${escapeHtml(column)}</th>`).join("")}</tr></thead>
  <tbody>
    ${table.rows.map((row) => `<tr>${table.columns.map((column) => `<td style="${tdStyle}">${escapeHtml(row[column] ?? "")}</td>`).join("")}</tr>`).join("\n    ")}
  </tbody>
</table>
<p style="${noteStyle}"><strong>Note.</strong> ${escapeHtml(table.note)}</p>`;
}

function formatNumber(value, digits = 3) {
  const number = Number(value);
  return Number.isFinite(number) ? number.toFixed(digits) : "";
}

function formatInteger(value) {
  const number = Number(value);
  return Number.isFinite(number) ? Math.round(number).toLocaleString("en-US") : "";
}

function formatSci(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number.toExponential(2) : "";
}

function formatPercent(value) {
  const number = Number(value);
  return Number.isFinite(number) ? `${(number * 100).toFixed(1)}%` : "";
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
